// Generated by CoffeeScript 1.10.0
var Bunkei, JouhouKougakuka200E, JouhouKougakuka200EO, JouhouKougakuka200O, JouhouKougakuka300E, JouhouKougakuka300EO, JouhouKougakuka300O, JouhouKougakukei200, JouhouKougakukei300, Nigai2nd, add, list, main, rev, update, vm;

JouhouKougakuka200EO = [];

JouhouKougakuka200EO[0] = ["#cff", "Mon,56,プログラミング第一O", "Mon,78,確率と統計O", "Mon,56,情報実験第一E(5678)", "Mon,78,情報実験第一E(5678)", "Thu,56,プログラミング第一E", "Thu,78,確率と統計E", "Thu,56,情報実験第一O(5678)", "Thu,78,情報実験第一O(5678)", "Fri,78,フーリエ変換とラプラス変換EO"];

JouhouKougakuka200EO[1] = ["#cff", "Mon,56,プログラミング第一O", "Mon,78,確率と統計O", "Mon,56,情報実験第一E(5678)", "Mon,78,情報実験第一E(5678)", "Tue,56,論理回路理論EO", "Tue,78,フーリエ変換とラプラス変換EO", "Thu,56,プログラミング第一E", "Thu,78,確率と統計E", "Thu,56,情報実験第一O(5678)", "Thu,78,情報実験第一O(5678)", "Fri,12,論理回路理論EO(1234)", "Fri,34,論理回路理論EO(1234)"];

JouhouKougakuka300EO = [];

JouhouKougakuka300EO[0] = ["#9cc", "Mon,12,関数解析学O", "Mon,34,離散構造とアルゴリズムO", "Mon,56,離散構造とアルゴリズムE", "Mon,78,ディジタル通信", "Mon,12,情報実験第三E(1234)", "Mon,34,情報実験第三E(1234)", "Mon,56,計算機アーキテクチャ第一O", "Tue,12,信号処理", "Tue,34,情報実験第三O", "Tue,56,関数解析学E", "Tue,78,計算機ネットワーク", "Tue,34,プログラミング第三E", "Tue,56,プログラミング第三O", "Thu,12,人工知能基礎E", "Thu,34,代数系と符号理論E", "Thu,56,集積回路設計", "Thu,78,代数系と符号理論O", "Thu,12,情報実験第三O(1234)", "Thu,34,情報実験第三O(1234)", "Thu,78,計算機アーキテクチャ第一E", "Fri,34,人工知能基礎O", "Fri,56,離散構造とアルゴリズムEO", "Fri,34,情報実験第三E", "Fri,56,代数系と符号理論EO"];

JouhouKougakuka300EO[1] = ["#9cc", "Mon,12,関数解析学O", "Mon,56,計算機アーキテクチャ第一O", "Mon,78,ディジタル通信", "Mon,12,情報実験第三E(1234)", "Mon,34,情報実験第三E(1234)", "Tue,12,信号処理", "Tue,34,情報実験第三O", "Tue,56,関数解析学E", "Tue,78,離散構造とアルゴリズムO", "Tue,34,プログラミング第三E", "Tue,56,プログラミング第三O", "Tue,78,代数系と符号理論E", "Tue,78,計算機ネットワーク", "Thu,12,人工知能基礎E", "Thu,56,計算機アーキテクチャ第一E", "Thu,78,集積回路設計", "Thu,12,情報実験第三O(1234)", "Thu,34,情報実験第三O(1234)", "Fri,34,人工知能基礎O", "Fri,56,離散構造とアルゴリズムO", "Fri,34,情報実験第三E", "Fri,56,代数系と符号理論E", "Fri,56,離散構造とアルゴリズムE(5678)", "Fri,78,離散構造とアルゴリズムE(5678)", "Fri,56,代数系と符号理論O(5678)", "Fri,78,代数系と符号理論O(5678)"];

JouhouKougakuka200E = [];

JouhouKougakuka200E[0] = ["#cff", "Mon,56,情報実験第一E(5678)", "Mon,78,情報実験第一E(5678)", "Thu,56,プログラミング第一E", "Thu,78,確率と統計E", "Fri,78,フーリエ変換とラプラス変換EO"];

JouhouKougakuka200E[1] = ["#cff", "Mon,56,情報実験第一E(5678)", "Mon,78,情報実験第一E(5678)", "Tue,56,論理回路理論EO", "Tue,78,フーリエ変換とラプラス変換EO", "Thu,56,プログラミング第一E", "Thu,78,確率と統計E", "Fri,12,論理回路理論EO(1234)", "Fri,34,論理回路理論EO(1234)"];

JouhouKougakuka300E = [];

JouhouKougakuka300E[0] = ["#9cc", "Mon,56,離散構造とアルゴリズムE", "Mon,78,ディジタル通信", "Mon,12,情報実験第三E(1234)", "Mon,34,情報実験第三E(1234)", "Tue,12,信号処理", "Tue,56,関数解析学E", "Tue,78,計算機ネットワーク", "Tue,34,プログラミング第三E", "Thu,12,人工知能基礎E", "Thu,34,代数系と符号理論E", "Thu,56,集積回路設計", "Thu,78,計算機アーキテクチャ第一E", "Fri,56,離散構造とアルゴリズムEO", "Fri,34,情報実験第三E", "Fri,56,代数系と符号理論EO"];

JouhouKougakuka300E[1] = ["#9cc", "Mon,78,ディジタル通信", "Mon,12,情報実験第三E(1234)", "Mon,34,情報実験第三E(1234)", "Tue,12,信号処理", "Tue,56,関数解析学E", "Tue,34,プログラミング第三E", "Tue,78,代数系と符号理論E", "Tue,78,計算機ネットワーク", "Thu,12,人工知能基礎E", "Thu,56,計算機アーキテクチャ第一E", "Thu,78,集積回路設計", "Fri,34,情報実験第三E", "Fri,56,代数系と符号理論E", "Fri,56,離散構造とアルゴリズムE(5678)", "Fri,78,離散構造とアルゴリズムE(5678)"];

JouhouKougakuka200O = [];

JouhouKougakuka200O[0] = ["#cff", "Mon,56,プログラミング第一O", "Mon,78,確率と統計O", "Thu,56,情報実験第一O(5678)", "Thu,78,情報実験第一O(5678)", "Fri,78,フーリエ変換とラプラス変換EO"];

JouhouKougakuka200O[1] = ["#cff", "Mon,56,プログラミング第一O", "Mon,78,確率と統計O", "Tue,56,論理回路理論EO", "Tue,78,フーリエ変換とラプラス変換EO", "Thu,56,情報実験第一O(5678)", "Thu,78,情報実験第一O(5678)", "Fri,12,論理回路理論EO(1234)", "Fri,34,論理回路理論EO(1234)"];

JouhouKougakuka300O = [];

JouhouKougakuka300O[0] = ["#9cc", "Mon,12,関数解析学O", "Mon,34,離散構造とアルゴリズムO", "Mon,78,ディジタル通信", "Mon,56,計算機アーキテクチャ第一O", "Tue,12,信号処理", "Tue,34,情報実験第三O", "Tue,78,計算機ネットワーク", "Tue,56,プログラミング第三O", "Thu,56,集積回路設計", "Thu,78,代数系と符号理論O", "Thu,12,情報実験第三O(1234)", "Thu,34,情報実験第三O(1234)", "Fri,34,人工知能基礎O", "Fri,56,離散構造とアルゴリズムEO", "Fri,56,代数系と符号理論EO"];

JouhouKougakuka300O[1] = ["#9cc", "Mon,12,関数解析学O", "Mon,56,計算機アーキテクチャ第一O", "Mon,78,ディジタル通信", "Tue,12,信号処理", "Tue,34,情報実験第三O", "Tue,78,離散構造とアルゴリズムO", "Tue,56,プログラミング第三O", "Tue,78,計算機ネットワーク", "Thu,78,集積回路設計", "Thu,12,情報実験第三O(1234)", "Thu,34,情報実験第三O(1234)", "Fri,34,人工知能基礎O", "Fri,56,離散構造とアルゴリズムO", "Fri,56,代数系と符号理論O(5678)", "Fri,78,代数系と符号理論O(5678)"];

JouhouKougakukei200 = [];

JouhouKougakukei200[0] = ["#99f", "Tue,78,計算基礎論EO", "Fri,12,計算基礎論EO(1234)", "Fri,34,計算基礎論EO(1234)"];

JouhouKougakukei200[1] = ["#99f"];

JouhouKougakukei300 = [];

JouhouKougakukei300[0] = ["#66c", "Tue,12,コンパイラ構成", "Fri,56,先端情報工学"];

JouhouKougakukei300[1] = ["#66c", "Tue,12,コンパイラ構成", "Fri,56,先端情報工学"];

Bunkei = [];

Bunkei[0] = ["#f99", "Tue,56,文系200", "Tue,78,文系300", "Fri,56,文系200", "Fri,78,文系300"];

Bunkei[1] = ["#f99", "Mon,12,文系200", "Mon,34,文系300", "Wed,34,文系300", "Thu,12,文系200"];

Nigai2nd = [];

Nigai2nd[0] = ["#ff9", "Wed,56,二外中級1"];

Nigai2nd[1] = ["#ff9", "Wed,56,二外中級2"];

rev = {
  "Mon": 1,
  "Tue": 2,
  "Wed": 3,
  "Thu": 4,
  "Fri": 5,
  "Other": 6,
  "1": 1,
  "2": 2,
  "3": 3,
  "4": 4,
  "5": 5,
  "6": 6,
  "12": 1,
  "34": 2,
  "56": 3,
  "78": 4,
  "910": 5
};

add = function(r, items) {
  var color, i, item, k, ref, results;
  color = r[0];
  results = [];
  for (i = k = 1, ref = r.length; 1 <= ref ? k < ref : k > ref; i = 1 <= ref ? ++k : --k) {
    item = r[i].split(',');
    results.push(items[rev[item[1]]][rev[item[0]]].push([color, item[2]]));
  }
  return results;
};

vm = [];

list = [JouhouKougakuka200E, JouhouKougakukei200, Bunkei, Nigai2nd, JouhouKougakuka300E, JouhouKougakukei300];

update = function() {
  var col, i, it, j, k, l, len, len1, m, n, ref, ref1, ref2, results, row, x;
  row = ",1～2,3～4,5～6,7～8,9～10,その他".split(',');
  col = ",月,火,水,木,金,その他".split(',');
  ref = [0, 1];
  results = [];
  for (k = 0, len = ref.length; k < len; k++) {
    x = ref[k];
    vm[x].items = [];
    for (i = l = 0, ref1 = row.length; 0 <= ref1 ? l < ref1 : l > ref1; i = 0 <= ref1 ? ++l : --l) {
      for (j = m = 0, ref2 = col.length; 0 <= ref2 ? m < ref2 : m > ref2; j = 0 <= ref2 ? ++m : --m) {
        if (j === 0) {
          vm[x].items[i] = [];
          vm[x].items[i][j] = row[i];
        } else if (i === 0) {
          vm[x].items[i][j] = col[j];
        } else {
          vm[x].items[i][j] = [];
        }
      }
    }
    for (n = 0, len1 = list.length; n < len1; n++) {
      it = list[n];
      add(it[x], vm[x].items);
    }
    results.push((function() {
      var o, ref3, results1;
      results1 = [];
      for (i = o = 1, ref3 = row.length; 1 <= ref3 ? o < ref3 : o > ref3; i = 1 <= ref3 ? ++o : --o) {
        results1.push((function() {
          var p, ref4, results2;
          results2 = [];
          for (j = p = 1, ref4 = col.length; 1 <= ref4 ? p < ref4 : p > ref4; j = 1 <= ref4 ? ++p : --p) {
            if (vm[x].items[i][j].length === 0) {
              results2.push(vm[x].items[i][j] = [["#fff", ":sobaya:"]]);
            } else {
              results2.push(void 0);
            }
          }
          return results2;
        })());
      }
      return results1;
    })());
  }
  return results;
};

main = function() {
  var k, len, ref, x;
  new Vue({
    el: "#controller",
    methods: {
      switchToE: function() {
        var i, k, ref;
        for (i = k = 0, ref = list.length; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
          if (list[i] === JouhouKougakuka200O || list[i] === JouhouKougakuka200EO) {
            list[i] = JouhouKougakuka200E;
          }
          if (list[i] === JouhouKougakuka300O || list[i] === JouhouKougakuka300EO) {
            list[i] = JouhouKougakuka300E;
          }
        }
        return update();
      },
      switchToO: function() {
        var i, k, ref;
        for (i = k = 0, ref = list.length; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
          if (list[i] === JouhouKougakuka200E || list[i] === JouhouKougakuka200EO) {
            list[i] = JouhouKougakuka200O;
          }
          if (list[i] === JouhouKougakuka300E || list[i] === JouhouKougakuka300EO) {
            list[i] = JouhouKougakuka300O;
          }
        }
        return update();
      },
      switchToEO: function() {
        var i, k, ref;
        for (i = k = 0, ref = list.length; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
          if (list[i] === JouhouKougakuka200E || list[i] === JouhouKougakuka200O) {
            list[i] = JouhouKougakuka200EO;
          }
          if (list[i] === JouhouKougakuka300E || list[i] === JouhouKougakuka300O) {
            list[i] = JouhouKougakuka300EO;
          }
        }
        return update();
      }
    }
  });
  ref = [0, 1];
  for (k = 0, len = ref.length; k < len; k++) {
    x = ref[k];
    vm[x] = new Vue({
      el: "#Q" + (x + 1),
      data: {
        items: {}
      }
    });
  }
  return update();
};

window.onload = main;
